In [1]:
import cv2
from keras.models import load_model
import numpy as np
model = load_model('keras_model.h5')
cap = cv2.VideoCapture(0)
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

while True: 
    ret, frame = cap.read()
    resized_frame = cv2.resize(frame, (224, 224), interpolation = cv2.INTER_AREA)
    image_np = np.array(resized_frame)
    normalized_image = (image_np.astype(np.float32) / 127.0) - 1 # Normalize the image
    data[0] = normalized_image
    prediction = model.predict(data)
    if prediction[0][0] > 0.5:
        print("Rock")
    elif prediction[0][1] > 0.5:
        print("Paper")
    elif prediction[0][2] > 0.5:
        print("Scissor")
    else:
        print("Nothing")
    
    cv2.imshow('frame', frame)
    # Press q to close the window
    print(prediction)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
            
# After the loop release the cap object
cap.release()
# Destroy all the windows
cv2.destroyAllWindows()

1/1 [==============================] - 1s 738ms/step
Nothing
[[1.7302756e-06 1.4213938e-04 7.7378508e-07 9.9985528e-01]]
1/1 [==============================] - 0s 31ms/step
Nothing
[[2.0653775e-04 1.0977436e-04 1.2691518e-06 9.9968243e-01]]
1/1 [==============================] - 0s 44ms/step
Nothing
[[2.4669760e-04 1.0586780e-04 1.2561289e-06 9.9964619e-01]]
1/1 [==============================] - 0s 38ms/step
Nothing
[[2.7239401e-04 1.2883545e-04 6.9760961e-07 9.9959809e-01]]
1/1 [==============================] - 0s 41ms/step
Nothing
[[3.4759619e-04 1.3466268e-04 9.4384205e-07 9.9951684e-01]]
1/1 [==============================] - 0s 41ms/step
Nothing
[[1.8951826e-04 1.4633583e-04 1.0090351e-06 9.9966311e-01]]
1/1 [==============================] - 0s 37ms/step
Nothing
[[1.5558705e-04 9.0168476e-05 5.9412497e-07 9.9975365e-01]]
1/1 [==============================] - 0s 39ms/step
Nothing
[[1.0588125e-04 5.7515655e-05 3.9138939e-07 9.9983609e-01]]
1/1 [==============================] - 